# Site settings
title: åˆ†æ åˆ†äº«
SEOTitle: ç‹å¤å¤©çš„ä¸ªäººä¸»é¡µ | â¤â¤â¤â¤â¤
header-img: img/post-bg-desk.jpg
email: wangxiatian@360-sh.com
description: "Every failure is leading towards success."
keyword: ""
url: "http://jimmymicrosun.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/jimmymicrosun.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "My first blog ğŸ‘"
sidebar-avatar: /img/5760CD28-0F53-4E5E-A4C3-731CB2A6DE2F.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    jimmymicrosun
facebook_username:  
jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: ture    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: 553196fe961dc01fac25                            #ç”Ÿæˆçš„clientID
  clientSecret: b71e7d83e9e3c72e16d0d7e8f8484a430ea7787b    #ç”Ÿæˆçš„clientSecret
  repo: jimmymicrosun.github.io    #ä»“åº“åç§°
  owner: jimmymicrosun    #githubç”¨æˆ·å
  admin: jimmymicrosun
 
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
ba_track_id: 52ac1dc2a9bafa8362e8227aab49ebd8

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 0              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "FreeBuf",
        href: "https://www.freebuf.com"
    },{
        title: "å®‰å…¨å®¢",
        href: "https://www.anquanke.com"
    },{
        title: "SecWiki",
        href: "https://www.sec-wiki.com/news"
    },{
        title: "360ä¼ä¸šå®‰å…¨",
        href: "https://b.360.cn/"
    }
]
